server:
  port: 3000
  logger:
    - error
    - warn
db:
  type: "postgres"
  port: 5432
  synchronize: true
  database: "resource_manager"
  host: "127.0.0.1"
  username: "postgres"
  password: "casa1234"
object-store:
  endPoint: "127.0.0.1"
  port: 9090
  accessKey: "minio"
  secretKey: "minio123"
  useSSL: false
  